import {useState} from 'react';
import {CalendarDays, CalendarPlus, CheckCircle2, Pencil, Plus, Trash2, X} from 'lucide-react';
import {ApptStatus, APPT_STATUS, APPT_TYPES, Appointment, Patient} from '../types';
import {addDays, dateLabel, dayLabel, id, stamp, timeLabel, timeRange, today, weekDay} from '../lib/format';
import {Badge, Confirm, Empty, Field, PageTitle, Stat, useEscape} from './ui';

type Range='Today'|'Upcoming'|'All';

export function Appointments({appointments,setAppointments,patients,onOpen}:{appointments:Appointment[];setAppointments:(a:Appointment[])=>void;patients:Patient[];onOpen:(id:string)=>void}){
 const[range,setRange]=useState<Range>('Today');const[day,setDay]=useState(today());
 const[form,setForm]=useState<Appointment|null>(null);const[ask,setAsk]=useState<{t:string;m:string;run:()=>void}|null>(null);
 const t=today(),custom=day!==t;
 const add=()=>setForm({id:id('ap_',appointments.map(a=>a.id)),patientId:patients[0]?patients[0].id:'',date:day,startTime:'10:00',endTime:'10:45',type:APPT_TYPES[1],status:'Scheduled',createdAt:stamp(),updatedAt:stamp()});
 const set=(k:keyof Appointment,v:Appointment[keyof Appointment])=>setForm(f=>f?{...f,[k]:v}:f);
 const save=(a:Appointment)=>{const row={...a,date:a.date||t,updatedAt:stamp()};setAppointments([...appointments.filter(x=>x.id!==a.id),row]);setForm(null)};
 const del=(a:Appointment)=>{setAppointments(appointments.filter(x=>x.id!==a.id));setForm(null)};
 const patch=(a:Appointment,status:ApptStatus)=>setAppointments(appointments.map(x=>x.id===a.id?{...x,status,updatedAt:stamp()}:x));
 const editing=!!form&&appointments.some(x=>x.id===form.id);useEscape(()=>setForm(null));
 const nameOf=(pid:string)=>{const q=patients.find(x=>x.id===pid);return q?q.name:'Unknown patient'};
 const go=(pid:string)=>{if(patients.some(x=>x.id===pid))onOpen(pid)};
 const view=appointments.filter(a=>custom?a.date===day:range==='Today'?a.date===t:range==='Upcoming'?a.date>=t:true);
 const list=view.slice().sort((a,b)=>(a.date+a.startTime).localeCompare(b.date+b.startTime));
 const todays=appointments.filter(a=>a.date===t);
 const upcoming=appointments.filter(a=>a.date>=t&&a.status==='Scheduled');
 const week=appointments.filter(a=>a.date>=t&&a.date<=addDays(t,7));
 const groups=list.map(a=>a.date).filter((d,i,arr)=>arr.indexOf(d)===i);
 return <section className="content"><PageTitle eyebrow="SCHEDULE" title="Appointments" text="Book, reschedule and track patient appointments."><button className="primary" onClick={add} disabled={!patients.length}><Plus size={17}/> New appointment</button></PageTitle>
 <div className="stats"><Stat icon={<CalendarDays/>} label="Today" value={todays.length} tone="blue"/><Stat icon={<CalendarPlus/>} label="Upcoming scheduled" value={upcoming.length} tone="blue"/><Stat icon={<CheckCircle2/>} label="Next 7 days" value={week.length} tone="green"/><Stat icon={<CalendarDays/>} label="No shows" value={appointments.filter(a=>a.status==='No Show').length} tone="red"/></div>
 <div className="filterBar"><div className="segmented">{(['Today','Upcoming','All'] as Range[]).map(r=><button key={r} aria-pressed={!custom&&range===r} className={(custom?false:range===r)?'sel':''} onClick={()=>{setRange(r);setDay(t)}}>{r}</button>)}</div><label className="filterField">Date<input type="date" value={day} onChange={e=>{setDay(e.target.value||t);setForm(f=>f?{...f,date:e.target.value||t}:f)}}/></label>{custom&&<button className="linkBtn" onClick={()=>{setDay(t);setRange('Today')}}>Back to today</button>}<span className="filterHint">{list.length} shown  |  {dateLabel(custom?day:t)}</span></div>
 <div className="card patientCard">{!patients.length&&<Empty icon={<CalendarDays size={22}/>} text="Add a patient first" hint="Appointments are linked to a patient record."/>}{!!patients.length&&!list.length&&<Empty icon={<CalendarDays size={22}/>} text="No appointments in this view" hint="Use New appointment to book a slot."/>}
 {groups.map(d=><div className="apptGroup" key={d}><div className="apptGroupDate"><b>{dayLabel(d)}</b><span>{weekDay(d)}  |  {list.filter(a=>a.date===d).length} booked</span></div><div className="table apptTable"><div className="tr th"><span>Time</span><span>Patient</span><span>Type</span><span>Status</span><span>Update</span><span></span></div>{list.filter(a=>a.date===d).map(a=><div className="tr row" key={a.id}><b>{timeRange(a.startTime,a.endTime)}</b><button className="patientLink" onClick={()=>go(a.patientId)}>{nameOf(a.patientId)}<small>{a.notes||a.id}</small></button><span>{a.type}</span><span><Badge status={a.status}/></span><span><select aria-label={`Status for ${nameOf(a.patientId)} on ${dateLabel(a.date)}`} className={'apptStatus '+a.status.toLowerCase().replace(' ','-')} value={a.status} onChange={e=>patch(a,e.target.value as ApptStatus)}>{APPT_STATUS.map(s=><option key={s}>{s}</option>)}</select></span><span className="rowActions"><button className="iconBtn" title="Edit appointment" aria-label={'Edit appointment on '+dateLabel(a.date)+' at '+timeLabel(a.startTime)} onClick={()=>setForm({...a})}><Pencil size={16}/></button><button className="iconBtn" title="Delete appointment" aria-label={'Delete appointment on '+dateLabel(a.date)} onClick={()=>setAsk({t:'Delete this appointment?',m:nameOf(a.patientId)+' on '+dateLabel(a.date)+' at '+timeLabel(a.startTime)+' will be removed from the schedule. This cannot be undone.',run:()=>del(a)})}><Trash2 size={16}/></button></span></div>)}</div></div>)}</div>
 {form&&<div className="modalWrap"><div className="modal" role="dialog" aria-modal="true" aria-label={editing?'Edit appointment':'New appointment'}><div className="modalHead"><div><h3>{editing?'Edit appointment':'New appointment'}</h3><p>Booked by the clinic for the selected patient.</p></div><button className="close" aria-label="Close" onClick={()=>setForm(null)}><X/></button></div><div className="formGrid"><Field label="Patient"><select value={form.patientId} onChange={e=>set('patientId',e.target.value)}>{patients.length?patients.map(x=><option key={x.id} value={x.id}>{x.name}  ({x.id})</option>):<option value="">No patients</option>}</select></Field><Field label="Appointment type"><select value={form.type} onChange={e=>set('type',e.target.value)}>{APPT_TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Date"><input type="date" value={form.date} onChange={e=>set('date',e.target.value)}/></Field><Field label="Status"><select value={form.status} onChange={e=>set('status',e.target.value as ApptStatus)}>{APPT_STATUS.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Start time"><input type="time" value={form.startTime} onChange={e=>set('startTime',e.target.value)}/></Field><Field label="End time"><input type="time" value={form.endTime} onChange={e=>set('endTime',e.target.value)}/></Field><Field label="Notes" full><textarea value={form.notes||''} onChange={e=>set('notes',e.target.value)}/></Field></div><div className="formActions"><button className="secondary" onClick={()=>setForm(null)}>Cancel</button><button className="primary" disabled={!form.patientId||!form.date} onClick={()=>save(form)}>{editing?'Save changes':'Book appointment'}</button></div></div></div>}
 {ask&&<Confirm title={ask.t} message={ask.m} onCancel={()=>setAsk(null)} onRun={()=>{ask.run();setAsk(null)}}/>}</section>
}
