import {useState} from 'react';
import {Filter, Pencil, Plus, Receipt, Trash2, Wallet, X} from 'lucide-react';
import {EXPENSE_CATS, Expense, ExpenseCat, Patient, PAY_METHODS, PayMethod} from '../types';
import {dateLabel, id, money, monthKey, monthLabel, num, sortDateDesc, stamp, sumBy, today} from '../lib/format';
import {Confirm, Empty, Field, PageTitle, Stat, useEscape} from './ui';

export function Expenses({expenses,setExpenses,patients}:{expenses:Expense[];setExpenses:(e:Expense[])=>void;patients:Patient[]}){
 const[q,setQ]=useState('');const[cat,setCat]=useState<'All'|ExpenseCat>('All');const[from,setFrom]=useState('');const[to,setTo]=useState('');
 const[form,setForm]=useState<Expense|null>(null);const[ask,setAsk]=useState<{t:string;m:string;run:()=>void}|null>(null);
 const nameOf=(pid?:string)=>{const q=patients.find(x=>x.id===pid);return q?q.name:''};
 const add=()=>setForm({id:id('ex_',expenses.map(e=>e.id)),date:today(),category:'Supplies',description:'',amount:0,paymentMethod:'Cash',createdAt:stamp()});
 const set=(k:keyof Expense,v:Expense[keyof Expense])=>setForm(f=>f?{...f,[k]:v}:f);
 const save=(e:Expense)=>{setExpenses([...expenses.filter(x=>x.id!==e.id),{...e,amount:Math.max(0,num(e.amount)),date:e.date||today()}]);setForm(null)};
 const del=(e:Expense)=>{setExpenses(expenses.filter(x=>x.id!==e.id));setForm(null)};
 const editing=!!form&&expenses.some(x=>x.id===form.id);useEscape(()=>setForm(null));
 const list=sortDateDesc(expenses.filter(e=>(cat==='All'||e.category===cat)&&(!from||e.date>=from)&&(!to||e.date<=to)&&(e.description+' '+e.category+' '+nameOf(e.patientId)).toLowerCase().includes(q.toLowerCase())),e=>e.date);
 const total=sumBy(list,e=>num(e.amount)),mk=monthKey(today()),thisMonth=sumBy(expenses.filter(e=>monthKey(e.date)===mk),e=>num(e.amount));
 const cats=EXPENSE_CATS.map(c=>({c,total:sumBy(expenses.filter(e=>e.category===c),e=>num(e.amount))})).filter(x=>x.total>0).sort((a,b)=>b.total-a.total);
 return <section className="content"><PageTitle eyebrow="CLINIC COSTS" title="Expenses" text="Track running costs separately from patient payments."><button className="primary" onClick={add}><Plus size={17}/> New expense</button></PageTitle>
 <div className="stats"><Stat icon={<Wallet/>} label={'This month ('+monthLabel(today())+')'} tone="red" text={money(thisMonth)}/><Stat icon={<Receipt/>} label="Filtered total" tone="blue" text={money(total)}/><Stat icon={<Filter/>} label="Entries shown" value={list.length} tone="blue"/><Stat icon={<Receipt/>} label="All time" tone="blue" text={money(sumBy(expenses,e=>num(e.amount)))}/></div>
 <div className="filterBar"><div className="searchFilter"><input aria-label="Search expenses by description, category or patient" placeholder="Search description, category or patient" value={q} onChange={e=>setQ(e.target.value)}/></div><label className="filterField">Category<select value={cat} onChange={e=>setCat(e.target.value as 'All'|ExpenseCat)}><option value="All">All categories</option>{EXPENSE_CATS.map(c=><option key={c}>{c}</option>)}</select></label><label className="filterField">From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="filterField">To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>{(from||to||cat!=='All'||q)&&<button className="linkBtn" onClick={()=>{setQ('');setCat('All');setFrom('');setTo('')}}>Clear filters</button>}<span className="filterHint">Total {money(total)}</span></div>
 <div className="expenseGrid"><div className="card patientCard">{!list.length&&<Empty icon={<Receipt size={22}/>} text="No expenses match this filter" hint="Add an expense to start tracking clinic running costs."/>}{list.length>0&&<div className="table expenseTable"><div className="tr th"><span>Date</span><span>Category</span><span>Description</span><span>Patient</span><span>Method</span><span>Amount</span><span></span></div>{list.map(e=><div className="tr row" key={e.id}><span>{dateLabel(e.date)}</span><span><span className="chip">{e.category}</span></span><span>{e.description||'-'}</span><span className="muted">{nameOf(e.patientId)||'-'}</span><span className="muted">{e.paymentMethod}</span><b>{money(e.amount)}</b><span className="rowActions"><button className="iconBtn" title="Edit expense" aria-label={'Edit expense '+(e.description||e.category)+' of '+money(e.amount)+' on '+dateLabel(e.date)} onClick={()=>setForm({...e})}><Pencil size={16}/></button><button className="iconBtn" title="Delete expense" aria-label={'Delete expense '+(e.description||e.category)+' of '+money(e.amount)+' on '+dateLabel(e.date)} onClick={()=>setAsk({t:'Delete this expense?',m:(e.description||e.category)+' of '+money(e.amount)+' on '+dateLabel(e.date)+' will be removed. This cannot be undone.',run:()=>del(e)})}><Trash2 size={16}/></button></span></div>)}</div>}</div>
 <div className="card"><div className="cardHead"><div><h3>By category</h3><p>All time</p></div></div><div className="catList">{cats.map(x=><div className="catRow" key={x.c}><span>{x.c}</span><div className="bar"><i style={{width:Math.max(4,Math.round(x.total/Math.max(1,cats[0].total)*100))+'%'}}/></div><b>{money(x.total)}</b></div>)}</div></div></div>
 {form&&<div className="modalWrap"><div className="modal" role="dialog" aria-modal="true" aria-label={editing?'Edit expense':'New expense'}><div className="modalHead"><div><h3>{editing?'Edit expense':'New expense'}</h3><p>Clinic running cost, optionally linked to a patient.</p></div><button className="close" aria-label="Close" onClick={()=>setForm(null)}><X/></button></div><div className="formGrid"><Field label="Date"><input type="date" value={form.date} onChange={e=>set('date',e.target.value)}/></Field><Field label="Category"><select value={form.category} onChange={e=>set('category',e.target.value as ExpenseCat)}>{EXPENSE_CATS.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Amount"><input type="number" min="0" value={form.amount} onChange={e=>set('amount',num(e.target.value))}/></Field><Field label="Payment method"><select value={form.paymentMethod} onChange={e=>set('paymentMethod',e.target.value as PayMethod)}>{PAY_METHODS.map(m=><option key={m}>{m}</option>)}</select></Field><Field label="Description" full><input value={form.description} placeholder="Yoga mats, rent, utilities" onChange={e=>set('description',e.target.value)}/></Field><Field label="Related patient" full><select value={form.patientId||''} onChange={e=>set('patientId',e.target.value||undefined)}><option value="">Not linked to a patient</option>{patients.map(x=><option key={x.id} value={x.id}>{x.name}  ({x.id})</option>)}</select></Field><Field label="Notes" full><textarea value={form.notes||''} onChange={e=>set('notes',e.target.value)}/></Field></div><div className="formActions"><button className="secondary" onClick={()=>setForm(null)}>Cancel</button><button className="primary" disabled={!form.date||form.amount<=0} onClick={()=>save(form)}>{editing?'Save changes':'Add expense'}</button></div></div></div>}
 {ask&&<Confirm title={ask.t} message={ask.m} onCancel={()=>setAsk(null)} onRun={()=>{ask.run();setAsk(null)}}/>}</section>
}
