import {useState} from 'react';
import {CheckCircle2, CreditCard, Pencil, Plus, Trash2, X} from 'lucide-react';
import {Patient, PAY_METHODS, Payment, PayMethod} from '../types';
import {dateLabel, id, money, num, sortDateDesc, stamp, today} from '../lib/format';
import {balanceOf, feeOf, ledgerOf, paidOf, statusOf, withFee, withLedger} from '../lib/payment';
import {Confirm, Empty, Field, Stat, useEscape} from './ui';

export function PaymentHistory({p,update}:{p:Patient;update:(p:Patient)=>void}){
 const all=p.payments||[],list=sortDateDesc(all,x=>x.date);
 const[form,setForm]=useState<Payment|null>(null);const[ask,setAsk]=useState<{t:string;m:string;run:()=>void}|null>(null);
 const fee=feeOf(p),paid=paidOf(p),balance=balanceOf(p),status=statusOf(p);
 const add=()=>setForm({id:id('pay_',all.map(x=>x.id)),patientId:p.id,date:today(),amount:Math.max(0,balance),paymentMethod:'Cash',createdAt:stamp()});
 const set=(k:keyof Payment,v:Payment[keyof Payment])=>setForm(f=>f?{...f,[k]:v}:f);
 const commit=(rows:Payment[])=>{update(withLedger(p,rows));setForm(null)};
 const save=(x:Payment)=>commit([...all.filter(y=>y.id!==x.id),{...x,amount:Math.max(0,num(x.amount)),date:x.date||today()}]);
 const editing=!!form&&all.some(x=>x.id===form.id);useEscape(()=>setForm(null));
 return <div className="detailGrid one"><div className="stats four"><Stat icon={<CreditCard/>} label="Total fee" tone="blue" text={money(fee)}/><Stat icon={<CheckCircle2/>} label="Total paid" tone="green" text={money(paid)}/><Stat icon={<CreditCard/>} label="Outstanding" tone="red" text={money(balance)}/><Stat icon={<CheckCircle2/>} label="Status" tone={balance>0?'red':'green'} text={status}/></div>
 <div className="card"><div className="cardHead"><div><h3>Payment history</h3><p>Outstanding = total fee - total payments</p></div><button className="primary" onClick={add}><Plus size={16}/> Add payment</button></div>
 <div className="feeBar"><label>Total treatment fee<input aria-label={`${p.name} treatment fee`} type="number" min="0" value={fee||''} placeholder="Enter fee" onChange={e=>update(withFee(p,num(e.target.value)))}/></label><div className="feeOut"><span>Total paid</span><b>{money(paid)}</b></div><div className="feeOut"><span>Outstanding</span><b className={balance>0?'redText':''}>{money(balance)}</b></div><div className="feeOut"><span>Status</span><span className={'paymentStatus '+status.toLowerCase().replace(' ','-')}>{status}</span></div></div>
 {ledgerOf(p)!==paid&&all.length>0&&<div className="reconcile"><span>Recorded payments total {money(ledgerOf(p))} but the patient record shows {money(paid)}.</span><button className="secondary" onClick={()=>update(withLedger(p,all))}>Use payment history</button></div>}
 {!all.length&&<Empty icon={<CreditCard size={22}/>} text="No payments recorded in the history" hint="Add a payment to keep a dated record of each collection."/>}
 {all.length>0&&<div className="table paymentHistoryTable"><div className="tr th"><span>Date</span><span>Method</span><span>Reference</span><span>Notes</span><span>Amount</span><span></span></div>{list.map(x=><div className="tr row paymentRow" key={x.id}><span>{dateLabel(x.date)}</span><span>{x.paymentMethod}</span><span className="muted">{x.reference||'-'}</span><span className="muted">{x.notes||'-'}</span><b>{money(x.amount)}</b><span className="rowActions"><button className="iconBtn" title="Edit payment" aria-label={'Edit payment from '+dateLabel(x.date)} onClick={()=>setForm({...x})}><Pencil size={16}/></button><button className="iconBtn" title="Delete payment" aria-label={'Delete payment from '+dateLabel(x.date)} onClick={()=>setAsk({t:'Delete this payment?',m:'The '+money(x.amount)+' payment from '+dateLabel(x.date)+' will be removed and the outstanding balance recalculated. This cannot be undone.',run:()=>commit(all.filter(y=>y.id!==x.id))})}><Trash2 size={16}/></button></span></div>)}</div>}
 <p className="legendNote">Total paid is stored on the patient record and is recalculated from the payments below. The Payments page can still set it directly.</p></div>
 {form&&<div className="modalWrap"><div className="modal" role="dialog" aria-modal="true" aria-label={editing?'Edit payment':'Add payment'}><div className="modalHead"><div><h3>{editing?'Edit payment':'Add payment'}</h3><p>Record a collection for {p.name}.</p></div><button className="close" aria-label="Close" onClick={()=>setForm(null)}><X/></button></div><div className="formGrid"><Field label="Payment date"><input type="date" value={form.date} onChange={e=>set('date',e.target.value)}/></Field><Field label="Amount received"><input type="number" min="0" value={form.amount} onChange={e=>set('amount',num(e.target.value))}/></Field><Field label="Payment method"><select value={form.paymentMethod} onChange={e=>set('paymentMethod',e.target.value as PayMethod)}>{PAY_METHODS.map(m=><option key={m}>{m}</option>)}</select></Field><Field label="Reference"><input value={form.reference||''} placeholder="UPI ref, receipt no." onChange={e=>set('reference',e.target.value)}/></Field><Field label="Notes" full><textarea value={form.notes||''} onChange={e=>set('notes',e.target.value)}/></Field></div><div className="formActions"><button className="secondary" onClick={()=>setForm(null)}>Cancel</button><button className="primary" disabled={!form.date||form.amount<=0} onClick={()=>save(form)}>{editing?'Save changes':'Add payment'}</button></div></div></div>}
 {ask&&<Confirm title={ask.t} message={ask.m} onCancel={()=>setAsk(null)} onRun={()=>{ask.run();setAsk(null)}}/>}</div>
}
