import {useState} from 'react';
import {ClipboardList, Pencil, Plus, Trash2, X} from 'lucide-react';
import {Patient, VISIT_TYPES, Visit} from '../types';
import {clamp, dateLabel, id, isNum, num, sortDateDesc, stamp, today} from '../lib/format';
import {Confirm, Empty, Field, useEscape} from './ui';

export function Visits({p,update}:{p:Patient;update:(p:Patient)=>void}){
 const all=p.visits||[],list=sortDateDesc(all,v=>v.date);
 const[form,setForm]=useState<Visit|null>(null);const[ask,setAsk]=useState<{t:string;m:string;run:()=>void}|null>(null);
 const add=()=>setForm({id:id('v_',all.map(v=>v.id)),patientId:p.id,date:today(),visitType:'Follow-up',painScore:isNum(p.painAfter)?p.painAfter:p.painBefore,createdAt:stamp()});
 const set=(k:keyof Visit,v:Visit[keyof Visit])=>setForm(f=>f?{...f,[k]:v}:f);
 const save=(v:Visit)=>{update({...p,visits:[...all.filter(x=>x.id!==v.id),{...v,date:v.date||today(),painScore:isNum(v.painScore)?clamp(v.painScore,0,10):undefined}]});setForm(null)};
 const del=(v:Visit)=>{update({...p,visits:all.filter(x=>x.id!==v.id)});setForm(null)};
 const editing=!!form&&all.some(x=>x.id===form.id);useEscape(()=>setForm(null));
 return <div className="card"><div className="cardHead"><div><h3>Visit history</h3><p>{all.length?all.length+' visits logged  |  latest '+dateLabel(list[0].date):'No follow-up visits recorded yet'}</p></div><button className="primary" onClick={add}><Plus size={16}/> Log visit</button></div>
 {!list.length&&<Empty icon={<ClipboardList size={22}/>} text="No visits recorded yet" hint="Log a visit to record pain, mobility and what was done in the session."/>}
 {list.length>0&&<div className="visitList">{list.map(v=><div className="visitRow" key={v.id}><div className="visitDate"><b>{dateLabel(v.date)}</b><span>{v.visitType}</span></div><div className="visitMain"><div className="visitMeta">{isNum(v.painScore)&&<span className="chip">Pain {v.painScore}/10</span>}{v.painScore==null&&<span className="chip">Pain not recorded</span>}{v.mobility!=null&&<span className="chip">Mobility {num(v.mobility)}/100</span>}<span className="mini">Logged {v.createdAt?new Date(v.createdAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):dateLabel(v.date)}</span></div>{v.treatment&&<p><b>Treatment:</b> {v.treatment}</p>}{v.exercises&&<p><b>Exercises:</b> {v.exercises}</p>}{v.notes&&<p>{v.notes}</p>}</div><div className="rowActions"><button className="iconBtn" title="Edit visit" aria-label={'Edit visit for '+p.name+' on '+dateLabel(v.date)} onClick={()=>setForm({...v})}><Pencil size={16}/></button><button className="iconBtn" title="Delete visit" aria-label={'Delete visit for '+p.name+' on '+dateLabel(v.date)} onClick={()=>setAsk({t:'Delete this visit?',m:'The visit on '+dateLabel(v.date)+' will be removed from '+p.name+'\u2019s record. This cannot be undone.',run:()=>del(v)})}><Trash2 size={16}/></button></div></div>)}</div>}
 {form&&<div className="modalWrap"><div className="modal" role="dialog" aria-modal="true" aria-label={editing?'Edit visit':'Log visit'}><div className="modalHead"><div><h3>{editing?'Edit visit':'Log visit'}</h3><p>Record what was done in this session.</p></div><button className="close" aria-label="Close" onClick={()=>setForm(null)}><X/></button></div><div className="formGrid"><Field label="Visit date"><input type="date" value={form.date} onChange={e=>set('date',e.target.value)}/></Field><Field label="Visit type"><select value={form.visitType} onChange={e=>set('visitType',e.target.value)}>{VISIT_TYPES.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Pain score (0-10)"><input type="number" min="0" max="10" value={form.painScore??''} placeholder="Optional" onChange={e=>set('painScore',e.target.value===''?undefined:clamp(num(e.target.value),0,10))}/></Field><Field label="Mobility score (0-100)"><input type="number" min="0" max="100" value={form.mobility??''} placeholder="Optional" onChange={e=>set('mobility',e.target.value===''?undefined:clamp(num(e.target.value),0,100))}/></Field><Field label="Treatment performed" full><textarea value={form.treatment||''} onChange={e=>set('treatment',e.target.value)}/></Field><Field label="Exercises prescribed" full><textarea value={form.exercises||''} onChange={e=>set('exercises',e.target.value)}/></Field><Field label="Notes" full><textarea value={form.notes||''} onChange={e=>set('notes',e.target.value)}/></Field></div><div className="formActions"><button className="secondary" onClick={()=>setForm(null)}>Cancel</button><button className="primary" disabled={!form.date} onClick={()=>save(form)}>{editing?'Save changes':'Add visit'}</button></div></div></div>}
 {ask&&<Confirm title={ask.t} message={ask.m} onCancel={()=>setAsk(null)} onRun={()=>{ask.run();setAsk(null)}}/>}</div>
}
