import {useState} from 'react';
import {AlertCircle, ImagePlus, Maximize2, Pencil, RotateCw, Trash2, X, ZoomIn, ZoomOut} from 'lucide-react';
import {Patient, XrayImage} from '../types';
import {dateLabel, id, sortDateDesc, today} from '../lib/format';
import {Confirm, Empty, Field, XrayBox, useEscape} from './ui';

export function Xrays({p,update}:{p:Patient;update:(p:Patient)=>void}){
 const all=p.xrays||[],list=sortDateDesc(all,r=>r.date);
 const[meta,setMeta]=useState<XrayImage|null>(null);const[view,setView]=useState<XrayImage|null>(null);
 const[zoom,setZoom]=useState(1);const[rot,setRot]=useState(0);const[edit,setEdit]=useState<XrayImage|null>(null);
  useEscape(()=>{if(edit)setEdit(null);else if(meta)setMeta(null);else if(view)setView(null)});
 const[ask,setAsk]=useState<{t:string;m:string;run:()=>void}|null>(null);
 const upload=(key:'before'|'after',file?:File)=>{if(!file)return;const r=new FileReader();r.onload=()=>update({...p,xray:{...p.xray,[key]:String(r.result)}});r.readAsDataURL(file)};
 const pick=(file?:File)=>{if(!file)return;const r=new FileReader();r.onload=()=>setMeta({id:id('img_',all.map(x=>x.id)),image:String(r.result),date:today(),title:'',bodyArea:'',notes:''});r.readAsDataURL(file)};
 const add=()=>{if(!meta)return;update({...p,xrays:[...all,meta]});setMeta(null)};
 const drop=(r:XrayImage)=>{update({...p,xrays:all.filter(x=>x.id!==r.id)});setView(view&&view.id===r.id?null:view);setEdit(null);setMeta(null)};
 const open=(r:XrayImage)=>{setView(r);setZoom(1);setRot(0)};
 return <div className="detailGrid one"><div className="card"><div className="cardHead"><div><h3>X-ray comparison</h3><p>Upload baseline and 3-month follow-up images.</p></div><ImagePlus size={18}/></div><div className="xrayGrid"><XrayBox title="Before treatment" image={p.xray.before} onFile={f=>upload('before',f)} onOpen={()=>p.xray.before&&open({id:'b',image:p.xray.before,date:p.visitDate,title:'Before treatment'})}/><div className="compareArrow">to</div><XrayBox title="After 3 months" image={p.xray.after} onFile={f=>upload('after',f)} onOpen={()=>p.xray.after&&open({id:'a',image:p.xray.after,date:p.followUpDate,title:'After 3 months'})}/></div><div className="imageNote"><AlertCircle size={16}/> Store only images and information appropriate for your clinic's privacy, consent and retention requirements.</div></div>
 <div className="card"><div className="cardHead"><div><h3>X-ray records</h3><p>{all.length?all.length+' record'+(all.length===1?'':'s')+'  |  newest first':'No dated X-ray records yet'}</p></div><label className="upload"><ImagePlus size={15}/> Upload X-ray<input type="file" accept="image/*" onChange={e=>pick(e.target.files?.[0])}/></label></div>
 {!all.length&&<Empty icon={<ImagePlus size={22}/>} text="No X-ray records yet" hint="Upload a scan with its date, body area and notes to build a dated record."/>}
 {all.length>0&&<div className="xrayList">{list.map(r=><div className="xrayRecord" key={r.id}><button className="xrayThumb" title={'View '+(r.title||r.bodyArea||'X-ray')} aria-label={'View X-ray for '+(r.bodyArea||r.title||'X-ray')+' from '+dateLabel(r.date)} onClick={()=>open(r)}><img src={r.image} alt={r.title||r.bodyArea||'X-ray record'}/><span className="zoomHint"><Maximize2 size={14}/></span></button><div className="xrayMeta"><b>{r.title||'X-ray record'}</b><span>{r.bodyArea||'Body area not set'}</span><span className="mini">{dateLabel(r.date)}{r.notes?'  |  '+r.notes:''}</span></div><div className="rowActions"><button className="iconBtn" title="Edit details" aria-label={'Edit X-ray details for '+(r.bodyArea||r.title||'X-ray')+' from '+dateLabel(r.date)} onClick={()=>setEdit({...r})}><Pencil size={16}/></button><button className="iconBtn" title="Delete X-ray" aria-label={'Delete X-ray from '+dateLabel(r.date)} onClick={()=>setAsk({t:'Delete this X-ray?',m:'The X-ray record from '+dateLabel(r.date)+' will be permanently removed from '+p.name+'\u2019s record. This cannot be undone.',run:()=>drop(r)})}><Trash2 size={16}/></button></div></div>)}</div>}
 <div className="imageNote"><AlertCircle size={16}/> Images are stored as data URLs in this device's local storage. Large files can exceed the storage limit.</div></div>
 {meta&&<div className="modalWrap"><div className="modal" role="dialog" aria-modal="true" aria-label="Save X-ray record"><div className="modalHead"><div><h3>Save X-ray record</h3><p>Add the details for this image.</p></div><button className="close" aria-label="Close" onClick={()=>setMeta(null)}><X/></button></div><div className="xrayPreview"><img src={meta.image} alt="X-ray to save"/></div><div className="formGrid"><Field label="Date"><input type="date" value={meta.date} onChange={e=>setMeta(m=>m?{...m,date:e.target.value}:m)}/></Field><Field label="Body area"><input value={meta.bodyArea||''} placeholder="Lower back" onChange={e=>setMeta(m=>m?{...m,bodyArea:e.target.value}:m)}/></Field><Field label="Title" full><input value={meta.title||''} placeholder="3-month follow-up" onChange={e=>setMeta(m=>m?{...m,title:e.target.value}:m)}/></Field><Field label="Notes" full><textarea value={meta.notes||''} onChange={e=>setMeta(m=>m?{...m,notes:e.target.value}:m)}/></Field></div><div className="formActions"><button className="secondary" onClick={()=>setMeta(null)}>Cancel</button><button className="primary" disabled={!meta.date} onClick={add}><ImagePlus size={16}/> Save X-ray</button></div></div></div>}
 {edit&&<div className="modalWrap"><div className="modal" role="dialog" aria-modal="true" aria-label="Edit X-ray details"><div className="modalHead"><div><h3>Edit X-ray details</h3><p>Update the metadata for this record.</p></div><button className="close" aria-label="Close" onClick={()=>setEdit(null)}><X/></button></div><div className="formGrid"><Field label="Date"><input type="date" value={edit.date} onChange={e=>setEdit(x=>x?{...x,date:e.target.value}:x)}/></Field><Field label="Body area"><input value={edit.bodyArea||''} onChange={e=>setEdit(x=>x?{...x,bodyArea:e.target.value}:x)}/></Field><Field label="Title" full><input value={edit.title||''} onChange={e=>setEdit(x=>x?{...x,title:e.target.value}:x)}/></Field><Field label="Notes" full><textarea value={edit.notes||''} onChange={e=>setEdit(x=>x?{...x,notes:e.target.value}:x)}/></Field></div><div className="formActions"><button className="secondary" onClick={()=>setEdit(null)}>Cancel</button><button className="primary" onClick={()=>{update({...p,xrays:all.map(x=>x.id===edit.id?edit:x)});setView(view&&view.id===edit.id?edit:view);setEdit(null)}}>Save changes</button></div></div></div>}
 {view&&<div className="viewer" role="dialog" aria-modal="true" aria-label="X-ray viewer"><div className="viewerBar"><b>{view.title||'X-ray record'}</b><span>{view.bodyArea||''}  |  {dateLabel(view.date)}</span><div className="viewerTools"><button className="iconBtn" title="Zoom out" aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(0.4,Math.round(z*10-1)/10))}><ZoomOut/></button><span className="zoomLevel">{Math.round(zoom*100)}%</span><button className="iconBtn" title="Zoom in" aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(4,Math.round(z*10+1)/10))}><ZoomIn/></button><button className="iconBtn" title="Rotate 90 degrees" aria-label="Rotate 90 degrees" onClick={()=>setRot(r=>(r+90)%360)}><RotateCw/></button><button className="iconBtn" title="Close viewer" aria-label="Close viewer" onClick={()=>setView(null)}><X/></button></div></div><button className="viewerImg" aria-label="Reset zoom to fit" onClick={()=>setZoom(1)}><img src={view.image} alt={view.title||'X-ray record'} style={{transform:'scale('+zoom+') rotate('+rot+'deg)'}}/></button><p className="legendNote">Click the image to reset zoom. Images are shown as stored; no analysis is performed.</p></div>}
 {ask&&<Confirm title={ask.t} message={ask.m} onCancel={()=>setAsk(null)} onRun={()=>{ask.run();setAsk(null)}}/>}</div>
}
